### ISSUE TITLE
Bashcov (Simplecov) failing

### ISSUE THREAD

**Issue by dalisoft** [infertux/bashcov#83]
## `.simplecov`

```ruby
SimpleCov.start do
  minimum_coverage 15
  add_filter "tests/"
  add_filter "/.git/"
  add_filter "bash_unit"

  command_name 'Unit Tests'
  coverage_dir 'coverage'
end
```

## Error

From **GitHub Actions** workflow error: https://github.com/dalisoft/release-me/actions/runs/8090808793/job/22108888404#step:5:16

```bash
rm -rf coverage && find . -iname '*.test.sh' | ROOT_DIR=$(pwd) xargs -L1 bashcov ./bash_unit --mute
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/Users/dalisoft/.gem/gems/simplecov-0.21.2/lib/simplecov.rb:354:in `start': coverage measurement is already setup (RuntimeError)
        from /Users/dalisoft/.gem/gems/simplecov-0.21.2/lib/simplecov.rb:354:in `start_coverage_with_criteria'
        from /Users/dalisoft/.gem/gems/simplecov-0.21.2/lib/simplecov.rb:343:in `start_coverage_measurement'
        from /Users/dalisoft/.gem/gems/simplecov-0.21.2/lib/simplecov.rb:59:in `start'
        from /Users/dalisoft/.gem/gems/bashcov-3.1.1/bin/bashcov:17:in `<top (required)>'
        from /Users/dalisoft/.gem/bin/bashcov:25:in `load'
        from /Users/dalisoft/.gem/bin/bashcov:25:in `<main>'
```

**Comment by infertux** [comment]
Fixed in #84
