### ISSUE TITLE
Problems with bashcov on bash for Windows

### ISSUE THREAD

**Issue by ale5000-git** [infertux/bashcov#87]
I run it like this (versin 3.1.2):
`BASHCOV_BASH_PATH='bash' bashcov -- ./my_script.sh`

and I get:
```
bashcov: warning: running as root is NOT recommended, Bashcov may not work properly.
C:/Ruby-x64/lib/ruby/gems/3.0.0/gems/bashcov-3.1.2/lib/bashcov/runner.rb:59:in `spawn': wrong file descriptor (4) (ArgumentError)
        from C:/Ruby-x64/lib/ruby/gems/3.0.0/gems/bashcov-3.1.2/lib/bashcov/runner.rb:59:in `block in run'
        from C:/Ruby-x64/lib/ruby/gems/3.0.0/gems/bashcov-3.1.2/lib/bashcov/runner.rb:118:in `with_xtrace_flag'
        from C:/Ruby-x64/lib/ruby/gems/3.0.0/gems/bashcov-3.1.2/lib/bashcov/runner.rb:58:in `run'
        from C:/Ruby-x64/lib/ruby/gems/3.0.0/gems/bashcov-3.1.2/bin/bashcov:12:in `<top (required)>'
        from C:/Ruby-x64/bin/bashcov:32:in `load'
        from C:/Ruby-x64/bin/bashcov:32:in `<main>'
```

1) It isn't root, the detection doesn't work.
2) If I comment the line 34 `options[fd] = fd # bind FDs to the child process`, then the script go on (obviously without this line doesn't work correctly).

**Comment by infertux** [comment]
I don't have a Windows machine to debug this but looking at the Ruby documentation, it seems Windows doesn't provide `IO.pipe`: [Not available on all platforms](https://www.rubydoc.info/stdlib/core/IO#pipe-class_method).
